SELECT
    idet.id,
    idet.name__en_us AS name,
    idet.description__en_us AS description,
    idet.preview_item__requirements__skill__profession__name__en_us AS profession_requirement,
    idet.preview_item__requirements__skill__profession__id AS profession_requirement_id,
    idet.preview_item__requirements__skill__display_string__en_us AS profession_requirement_display_string,
    idet.preview_item__requirements__level__display_string__en_us AS level_requirements,
    idet.preview_item__binding__name__en_us AS binding_type,
    idet.preview_item__unique_equipped__en_us AS unique_type,
    idet.preview_item__requirements__reputation__display_string__en_us AS reputation_requirement_display_string,
    idet.preview_item__requirements__reputation__faction__id as reputation_requirement_id,
    idet.modified_crafting__id AS modified_crafting_id,
    idet.preview_item__name_description__display_string__en_us AS special_subname,
    idet.preview_item__requirements__map__name__en_us AS map_requirement,
    idet.preview_item__requirements__map__id AS map_id,
    idet.preview_item__requirements__ability__spell__id AS ability_spell_id,
    idet.preview_item__requirements__playable_classes__display_string__en_us AS class_requirement,
    idet.preview_item__weapon__damage__display_string__en_us AS weapon_damage,
    idet.preview_item__weapon__damage__damage_class__name__en_us AS damage_type,
    idet.preview_item__weapon__attack_speed__display_string__en_us AS attack_speed,
    idet.preview_item__weapon__dps__display_string__en_us AS dps,
    idet.preview_item__durability__display_string__en_us AS durability,
    idet.preview_item__item_starts_quest__quest__id AS quest_id,
    idet.preview_item__socket_bonus__en_us AS socket_bonus,
    idet.preview_item__gem_properties__effect__en_us AS gem_stats,
    idet.preview_item__armor__display__display_string__en_us AS armor,
    idet.preview_item__shield_block__display__display_string__en_us AS shield_block,
    idet.preview_item__recipe__item__item__id AS recipe_id,
    idet.preview_item__charges__display_string__en_us AS use_charges,
    idet.preview_item__requirements__holiday__display_string__en_us AS holiday_requirements,
    idet.preview_item__requirements__playable_races__display_string__en_us AS race_requirements,
    idet.preview_item__set__item_set__name__en_us AS set_name,
    idet.preview_item__set__item_set__id AS set_id,
    idet.preview_item__modified_appearance_id AS modified_appearance_id,
    idet.preview_item__upgrades__display_string__en_us AS heirloom_upgrade_level,
    idet.preview_item__requirements__playable_specializations__display_string__en_us AS specializations_requirements,
    istat.type__name__en_us AS stat_type,
    istat.value AS value
FROM {{ source('raw_items', 'item_details') }} AS idet

LEFT JOIN {{ source('raw_items', 'item_details__preview_item__stats') }} AS istat ON istat._dlt_parent_id = idet._dlt_id